spring.application.name=campusbites

# MongoDB Connection
spring.data.mongodb.uri=mongodb+srv://sierradrex_db_user:GYmkcjRzLigPullG@campusbitescluster.od3gpyt.mongodb.net/CampusBitesDB?retryWrites=true&w=majority
